version: '3.8'
services:
  api:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/todos
      - PORT=3000
    depends_on:
      - db
    ports:
      - '3000:3000'
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - '5432:5432'
